### ISSUE TITLE
eslint ругается в этом месте? можешь прикрепить скрин в ишью?

### ISSUE THREAD

**Issue by kameas** [flowdel/flowdel.github.io#24]
https://github.com/flowdel/flowdel.github.io/blob/d24bccfe3b9dfeb8cd46e4a2eb6618149d7624a6/src/components/product/ProductDetails.vue#L129

**Comment by flowdel** [comment]
<img width="1178" alt="Снимок экрана 2020-08-19 в 17 53 11" src="https://user-images.githubusercontent.com/36550214/90650768-ea03ea00-e244-11ea-9dcc-cecde017e537.png">
